### ISSUE TITLE
New Convector Signature

### ISSUE THREAD

**Issue by DanijelMalik** [AMoo-Miki/homebridge-tuya-lan#44]
I've got two heater panels that visually look the same but they must be using different firmware. These are signatures for both of them:
The old one (working): {"2":30,"3":27,"4":"High","6":false,"7":true,"8":0}
The new one (not-working): {"1":true,"2":false,"3":30,"4":22,"5":0,"6":0,"7":"Low"}

From what I see parameters come in a different order. This a likely mapping (New => Old):
1 => 7
2 => 6
3 => 2
4 => 3
5 => 8
6 => ?
7 => 4

**Comment by AMoo-Miki** [comment]
@DanijelMalik, I just pushed some changes that should allow you to override the data-points; take a look [here](https://github.com/AMoo-Miki/homebridge-tuya-lan/wiki/Supported-Devices#heat-convectors).

Lemme know how it goes.

**Comment by chyumcha** [comment]
I'm facing a similar issue. 
Ready to handle Heater with signature {"2":24,"3":18,"4":"Low","6":false,"7":false,"8":0}

I've tried the override with 1 through to 8 but still no luck being able to turn on/off. 
Any ideas @AMoo-Miki 
how did you go @DanijelMalik
