### ISSUE TITLE
Failed to Discover.....

### ISSUE THREAD

**Issue by mrblack7** [AMoo-Miki/homebridge-tuya-lan#98]
Hey all,

I am trying to get a "Brilliant Smart Wifi plug" working with this plugin. I have successfully added it to the Tuya App and got the id and key, but when added to Homebridge it wasn't able to discover it.
So I then added the static IP to config.jason but gwtting the following.

```
Oct 10 10:24:30 raspberrypi homebridge[734]: [10/10/2019, 10:24:30 AM] [TuyaLan] Failed to discover Test Socket (60013016c44f33b0092f) in time but will connect via 192.168.0.250.
Oct 10 10:24:30 raspberrypi homebridge[734]: [10/10/2019, 10:24:30 AM] [TuyaLan] Connected to Test Socket
Oct 10 10:25:00 raspberrypi homebridge[734]: [TuyaAccessory] Socket had a problem and will reconnect to Test Socket (Error: ERR_PING_TIMED_OUT)
Oct 10 10:25:00 raspberrypi homebridge[734]: [TuyaAccessory] Closed connection with Test Socket
Oct 10 10:25:35 raspberrypi homebridge[734]: [TuyaAccessory] Socket had a problem and will reconnect to Test Socket (Error: ERR_PING_TIMED_OUT)
Oct 10 10:25:35 raspberrypi homebridge[734]: [TuyaAccessory] Closed connection with Test Socket
Oct 10 10:26:11 raspberrypi homebridge[734]: [TuyaAccessory] Socket had a problem and will reconnect to Test Socket (Error: ERR_PING_TIMED_OUT)
Oct 10 10:26:11 raspberrypi homebridge[734]: [TuyaAccessory] Closed connection with Test Socket
Oct 10 10:26:46 raspberrypi homebridge[734]: [TuyaAccessory] Socket had a problem and will reconnect to Test Socket (Error: ERR_PING_TIMED_OUT)
Oct 10 10:26:46 raspberrypi homebridge[734]: [TuyaAccessory] Closed connection with Test Socket
Oct 10 10:27:21 raspberrypi homebridge[734]: [TuyaAccessory] Socket had a problem and will reconnect to Test Socket (Error: ERR_PING_TIMED_OUT)
Oct 10 10:27:21 raspberrypi homebridge[734]: [TuyaAccessory] Closed connection with Test Socket
Oct 10 10:27:56 raspberrypi homebridge[734]: [TuyaAccessory] Socket had a problem and will reconnect to Test Socket (Error: ERR_PING_TIMED_OUT)
Oct 10 10:27:56 raspberrypi homebridge[734]: [TuyaAccessory] Closed connection with Test Socket
Oct 10 10:28:31 raspberrypi homebridge[734]: [TuyaAccessory] Socket had a problem and will reconnect to Test Socket (Error: ERR_PING_TIMED_OUT)
Oct 10 10:28:31 raspberrypi homebridge[734]: [TuyaAccessory] Closed connection with Test Socket
Oct 10 10:29:06 raspberrypi homebridge[734]: [TuyaAccessory] Socket had a problem and will reconnect to Test Socket (Error: ERR_PING_TIMED_OUT)
Oct 10 10:29:06 raspberrypi homebridge[734]: [TuyaAccessory] Closed connection with Test Socket
Oct 10 10:29:41 raspberrypi homebridge[734]: [TuyaAccessory] Socket had a problem and will reconnect to Test Socket (Error: ERR_PING_TIMED_OUT)
Oct 10 10:29:41 raspberrypi homebridge[734]: [TuyaAccessory] Closed connection with Test Socket
```

Any tips on how to proceed?

**Comment by mrblack7** [comment]
This was resolved by updating to the latest RC using ``npm i -g homebridge-tuya-lan@rc ``

**Comment by codyc1515** [comment]
I am still having this issue @AMoo-Miki 

Will this _rc_ branch be pushed out soon?
